source = 'src/attacus/flutter/embedder.h'
target = 'src/attacus_py/bindings/generated.cpp'

prefix = 'Flutter'
short_prefix = 'Im'

module = 'attacus_py'

flags = [
    '-std=c++20',
]

excludes = [
    'FlutterSize', #TODO: It says Size is already defined ...
    'FlutterPlatformMessage',
    'FlutterTask',
    'FlutterTaskRunner',
    'FlutterPlatformViewMutation',
    'FlutterPlatformView',
    'FlutterProjectArgs',
    'FlutterEngineAOTData',
    'FlutterEngineDartBuffer',

    'FlutterMetalExternalTexture',
    #'FlutterEngineProcTable',
    #'FlutterCompositor',
    #'FlutterTaskRunnerDescription',
    #'FlutterSoftwareRendererConfig',
    #'FlutterMetalRendererConfig',

    # Functions
    'FlutterEngineCreateAOTData',
    'FlutterEngineCollectAOTData',
    'FlutterEngineRun',
    'FlutterEngineShutdown',
    'FlutterEngineInitialize',
    'FlutterEngineDeinitialize',
    'FlutterEngineRunInitialized',
    'FlutterEngineSendWindowMetricsEvent',
    'FlutterEngineSendPointerEvent',
    'FlutterEngineSendPlatformMessage',
    'FlutterPlatformMessageReleaseResponseHandle',
    'FlutterEngineSendPlatformMessageResponse',
    'FlutterEngineRegisterExternalTexture',
    'FlutterEngineUnregisterExternalTexture',
    'FlutterEngineMarkExternalTextureFrameAvailable',
    'FlutterEngineUpdateSemanticsEnabled',
    'FlutterEngineUpdateAccessibilityFeatures',
    'FlutterEngineDispatchSemanticsAction',
    'FlutterEngineOnVsync',
    'FlutterEngineReloadSystemFonts',
    'FlutterEngineRunTask',
    'FlutterEngineUpdateLocales',
    'FlutterEnginePostDartObject',
    'FlutterEngineNotifyLowMemoryWarning',
    'FlutterEngineNotifyDisplayUpdate'
]

overloaded = [
]